name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        target: x86_64-pc-windows-gnu

    - name: Run fmt checks
      run: cargo fmt -- --check

  test-win:
    runs-on: windows-latest
    strategy:
      matrix:
        target:
          - i686-pc-windows-gnu
          - i686-pc-windows-msvc
          - x86_64-pc-windows-gnu
          - x86_64-pc-windows-msvc
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set default target
      run: |
        rustup default stable-${{ matrix.target }}
        rustup component add clippy

    - name: Run clippy
      run: cargo clippy
    
    - name: Run tests
      run: cargo test --all-features

  test-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        target:
          - x86_64-apple-darwin
        # - aarch64-apple-darwin
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set default target
      run: |
        rustup default stable-${{ matrix.target }}
        rustup component add clippy

    - name: Run clippy
      run: cargo clippy
    
    - name: Run tests
      run: cargo test --all-features

  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          # i686 /usr/bin/ld: cannot find Scrt1.o
          - i686-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set default target
      run: |
        rustup default stable-${{ matrix.target }}
        rustup component add clippy

    - name: Run clippy
      run: cargo clippy
    
    - name: Run tests
      run: cargo test --all-features
